MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
INPUT:
  # MIN_SIZE_TRAIN: 320
  # MAX_SIZE_TRAIN: 320
  # MIN_SIZE_TEST: 320
  # MAX_SIZE_TEST: 320
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
DATASETS:
  TRAIN: ("coco_qinghai_train_bquad",)
  TEST: ("coco_qinghai_test_bquad",)
DATALOADER:
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 100
TEST:
  IMS_PER_BATCH: 1
# OUTPUT_DIR: "./output/mapping-challenge"
OUTPUT_DIR: "./output/qinghai_lr0.001/e2e_faster_rcnn_R_50_C4_1x"
