MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "/home/jky-cuda8/.torch/models/X-101-64x4d.pkl"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 64
    WIDTH_PER_GROUP: 4
  MASK_ON: True
INPUT:
#   MIN_SIZE_TRAIN: 320
#   MAX_SIZE_TRAIN: 320
#   MIN_SIZE_TEST: 320
#   MAX_SIZE_TEST: 320
   MIN_SIZE_TRAIN: 512
   MAX_SIZE_TRAIN: 512
   MIN_SIZE_TEST: 512
   MAX_SIZE_TEST: 512
DATASETS:
  TRAIN: ("coco_fujian_train",)
  TEST: ("coco_fujian_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.00125
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 5
  CHECKPOINT_PERIOD: 5000
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: "./output/fujian"
