MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (1.0, 1.0, 1.0) # (0.83, 1.0, 1.2)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 10000 # 10000 # 20000 # 10000 # 1000
    POST_NMS_TOP_N_TEST:  2000 # 3000 # 5000 # 10000 # 2000 # 1000
    FPN_POST_NMS_TOP_N_TEST: 1500 # 3000 # 5000 # 1000
    NMS_THRESH: 0.9
  ROI_HEADS:
    USE_FPN: True
    NMS: 0.3
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  MASK_ON: False
  BQUAD_ON: True
INPUT:
  # MIN_SIZE_TRAIN: 320
  # MAX_SIZE_TRAIN: 320
  # MIN_SIZE_TEST: 320
  # MAX_SIZE_TEST: 320
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
DATASETS:
  TRAIN: ("coco_qinghai_urban_train_trec", "coco_qinghai_suburban_train_trec")
  TEST: ("coco_canada_2_demo",)
DATALOADER:
  NUM_WORKERS: 4
  SIZE_DIVISIBILITY: 32
SOLVER:
  #gpu 8
  #BASE_LR: 0.01
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  #STEPS: (120000, 160000)
  #MAX_ITER: 180000
  STEPS: (30000, 50000)
  MAX_ITER: 30000
  IMS_PER_BATCH: 3
  CHECKPOINT_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 3
# OUTPUT_DIR: "./output/mapping-challenge"
OUTPUT_DIR: "./output/coco_qinghai_urban_suburban/e2e_bquad_rcnn_X_101_32x8d_FPN_1x_gpu3_trec"
