MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
INPUT:
  # MIN_SIZE_TRAIN: 320
  # MAX_SIZE_TRAIN: 320
  # MIN_SIZE_TEST: 320
  # MAX_SIZE_TEST: 320
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
DATASETS:
  # TRAIN: ("coco_mapping_challenge_train",)
  # TEST: ("coco_mapping_challenge_val",)
  TRAIN: ("coco_qinghai_train",)
  TEST: ("coco_qinghai_test",)
DATALOADER:
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 5
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (80000, 120000)
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 5000
TEST:
  IMS_PER_BATCH: 1
# OUTPUT_DIR: "./output/mapping-challenge"
OUTPUT_DIR: "./output/coco_qinghai/e2e_mask_rcnn_R_101_FPN_1x_gpu1_baseline_batchsize5"
