MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "./imagenet/mobilenet_v2.pth.tar"
  BACKBONE:
    CONV_BODY: "MobileNetV2"
    OUT_CHANNELS: 96
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    MLP_HEAD_DIM: 1280
    FEATURE_EXTRACTOR: "MobileNetV2FeatureExtractor"
    PREDICTOR: "MobileNetV2Predictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: False
  BQUAD_ON: True
INPUT:
  # MIN_SIZE_TRAIN: 320
  # MAX_SIZE_TRAIN: 320
  # MIN_SIZE_TEST: 320
  # MAX_SIZE_TEST: 320
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
DATASETS:
  # TRAIN: ("coco_mapping_challenge_train",)
  # TEST: ("coco_mapping_challenge_val",)
  TRAIN: ("coco_qinghai_train_bquad",)
  TEST: ("coco_qinghai_test_bquad",)
DATALOADER:
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 5
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 2500
TEST:
  IMS_PER_BATCH: 1
# OUTPUT_DIR: "./output/mapping-challenge"
OUTPUT_DIR: "./output/qinghai_lr0.001/e2e_bquad_rcnn_MobileNetV2_1x_gpu1_bquad"
