MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
    USE_PANMULIMG_FPN: True
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    STEM_FUNC: "StemWithFixedBatchNormPansharpeningImg"
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  MASK_ON: False
  BQUAD_ON: True
INPUT:
  # MIN_SIZE_TRAIN: 320
  # MAX_SIZE_TRAIN: 320
  # MIN_SIZE_TEST: 320
  # MAX_SIZE_TEST: 320
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 512
DATASETS:
  TRAIN: ("coco_shandong_pansharpening_train_trec",)
  TEST: ("coco_shandong_pansharpening_test_trec",)
DATALOADER:
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
SOLVER:
  #gpu 8
  #BASE_LR: 0.01
  BASE_LR: 0.002
  WEIGHT_DECAY: 0.0001
  #STEPS: (120000, 160000)
  #MAX_ITER: 180000
  STEPS: (10000, 15000)
  MAX_ITER: 10000
  IMS_PER_BATCH: 3
  CHECKPOINT_PERIOD: 1000
TEST:
  IMS_PER_BATCH: 6
# OUTPUT_DIR: "./output/mapping-challenge"
OUTPUT_DIR: "./output/coco_shandong_pansharpening/e2e_PansharpeningImg_bquad_rcnn_X_101_32x8d_FPN_1x_gpu1_trec"
